### ISSUE TITLE
hi i am trying to use your code i am going same as you mentioned but getting  " esprima.error_handler.Error: Line 1: Unexpected token : "

### ISSUE THREAD

**Issue by dheeraj009joshi** [radian-software/unzuckify#2]
hi i am using your code to receive all the threads from messanger but i am getting some token issues can you help me 

the full trackback :- 
Traceback (most recent call last):
  File "C:\Users\dlove\OneDrive\Desktop\messanger_dm\unzuckify.py", line 424, in <module>
    main()
  File "C:\Users\dlove\OneDrive\Desktop\messanger_dm\unzuckify.py", line 420, in main
    do_main(args)
  File "C:\Users\dlove\OneDrive\Desktop\messanger_dm\unzuckify.py", line 391, in do_main
    inbox_data = get_inbox_data(inbox_js)
  File "C:\Users\dlove\OneDrive\Desktop\messanger_dm\unzuckify.py", line 236, in get_inbox_data
    esprima.parseScript(inbox_js, delegate=delegate)
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\esprima.py", line 100, in parseScript
    return parse(code, options, delegate, **kwargs)
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\esprima.py", line 79, in parse    
    ast = parser.parseModule() if isModule else parser.parseScript()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 2867, in parseScript
    body.append(self.parseStatementListItem())
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 1558, in parseStatementListItem
    statement = self.parseStatement()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 2292, in parseStatement
    statement = self.parseBlock()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 1570, in parseBlock
    block.append(self.parseStatementListItem())
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 1558, in parseStatementListItem
    statement = self.parseStatement()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 2287, in parseStatement
    statement = self.parseExpressionStatement()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 1820, in parseExpressionStatement
    self.consumeSemicolon()
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 535, in consumeSemicolon
    self.throwUnexpectedToken(self.lookahead)
  File "C:\Users\dlove\AppData\Local\Programs\Python\Python310\lib\site-packages\esprima\parser.py", line 237, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
esprima.error_handler.Error: Line 1: Unexpected token :

can you tell me how i can solve this

**Comment by dheeraj009joshi** [comment]
hi anyone there ?
